# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-06-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='shipping_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ShippingTypes'),
        ),
    ]
