import os
from tablib import Dataset

if __name__ == '__main__':
    os.environ.setdefault('DJANGO_SETTINGS_MODULE',
                          'turtle_beans.settings')

    import django
    django.setup()

    from django.db import connection
    from apps.accounts.models import Country, State, City




    unique_list = []

    zip_code_list = [
        "T0A",
"T0B",
"T0C",
"T0E",
"T0G",
"T0H",
"T0J",
"T0K",
"T0L",
"T0M",
"T0P",
"T0V",
"T1A",
"T1B",
"T1C",
"T1G",
"T1H",
"T1J",
"T1K",
"T1L",
"T1M",
"T1P",
"T1R",
"T1S",
"T1V",
"T1W",
"T1X",
"T1Y",
"T2A",
"T2B",
"T2C",
"T2E",
"T2G",
"T2H",
"T2J",
"T2K",
"T2L",
"T2M",
"T2N",
"T2P",
"T2R",
"T2S",
"T2T",
"T2V",
"T2W",
"T2X",
"T2Y",
"T2Z",
"T3A",
"T3B",
"T3C",
"T3E",
"T3G",
"T3H",
"T3J",
"T3K",
"T3L",
"T3M",
"T3N",
"T3P",
"T3R",
"T3Z",
"T4A",
"T4B",
"T4C",
"T4E",
"T4G",
"T4H",
"T4J",
"T4L",
"T4N",
"T4P",
"T4R",
"T4S",
"T4T",
"T4V",
"T4X",
"T5A",
"T5B",
"T5C",
"T5E",
"T5G",
"T5H",
"T5J",
"T5K",
"T5L",
"T5M",
"T5N",
"T5P",
"T5R",
"T5S",
"T5T",
"T5V",
"T5W",
"T5X",
"T5Y",
"T5Z",
"T6A",
"T6B",
"T6C",
"T6E",
"T6G",
"T6H",
"T6J",
"T6K",
"T6L",
"T6M",
"T6N",
"T6P",
"T6R",
"T6S",
"T6T",
"T6V",
"T6W",
"T6X",
"T7A",
"T7E",
"T7N",
"T7P",
"T7S",
"T7V",
"T7X",
"T7Y",
"T7Z",
"T8A",
"T8B",
"T8C",
"T8E",
"T8G",
"T8H",
"T8L",
"T8N",
"T8R",
"T8S",
"T8V",
"T8W",
"T8X",
"T9A",
"T9C",
"T9E",
"T9G",
"T9H",
"T9J",
"T9K",
"T9M",
"T9N",
"T9S",
"T9V",
"T9W",
"T9X",
"V0A",
"V0B",
"V0C",
"V0E",
"V0G",
"V0H",
"V0J",
"V0K",
"V0L",
"V0M",
"V0N",
"V0P",
"V0R",
"V0S",
"V0T",
"V0V",
"V0W",
"V0X",
"V1A",
"V1B",
"V1C",
"V1E",
"V1G",
"V1H",
"V1J",
"V1K",
"V1L",
"V1M",
"V1N",
"V1P",
"V1R",
"V1S",
"V1T",
"V1V",
"V1W",
"V1X",
"V1Y",
"V1Z",
"V2A",
"V2B",
"V2C",
"V2E",
"V2G",
"V2H",
"V2J",
"V2K",
"V2L",
"V2M",
"V2N",
"V2P",
"V2R",
"V2S",
"V2T",
"V2V",
"V2W",
"V2X",
"V2Y",
"V2Z",
"V3A",
"V3B",
"V3C",
"V3E",
"V3G",
"V3H",
"V3J",
"V3K",
"V3L",
"V3M",
"V3N",
"V3R",
"V3S",
"V3T",
"V3V",
"V3W",
"V3X",
"V3Y",
"V4A",
"V4B",
"V4C",
"V4E",
"V4G",
"V4K",
"V4L",
"V4M",
"V4N",
"V4P",
"V4R",
"V4S",
"V4T",
"V4V",
"V4W",
"V4X",
"V4Z",
"V5A",
"V5B",
"V5C",
"V5E",
"V5G",
"V5H",
"V5J",
"V5K",
"V5L",
"V5M",
"V5N",
"V5P",
"V5R",
"V5S",
"V5T",
"V5V",
"V5W",
"V5X",
"V5Y",
"V5Z",
"V6A",
"V6B",
"V6C",
"V6E",
"V6G",
"V6H",
"V6J",
"V6K",
"V6L",
"V6M",
"V6N",
"V6P",
"V6R",
"V6S",
"V6T",
"V6V",
"V6W",
"V6X",
"V6Y",
"V6Z",
"V7A",
"V7B",
"V7C",
"V7E",
"V7G",
"V7H",
"V7J",
"V7K",
"V7L",
"V7M",
"V7N",
"V7P",
"V7R",
"V7S",
"V7T",
"V7V",
"V7W",
"V7X",
"V7Y",
"V8A",
"V8B",
"V8C",
"V8G",
"V8J",
"V8K",
"V8L",
"V8M",
"V8N",
"V8P",
"V8R",
"V8S",
"V8T",
"V8V",
"V8W",
"V8X",
"V8Y",
"V8Z",
"V9A",
"V9B",
"V9C",
"V9E",
"V9G",
"V9H",
"V9J",
"V9K",
"V9L",
"V9M",
"V9N",
"V9P",
"V9R",
"V9S",
"V9T",
"V9V",
"V9W",
"V9X",
"V9Y",
"R0A",
"R0B",
"R0C",
"R0E",
"R0G",
"R0H",
"R0J",
"R0K",
"R0L",
"R0M",
"R1A",
"R1B",
"R1N",
"R2C",
"R2E",
"R2G",
"R2H",
"R2J",
"R2K",
"R2L",
"R2M",
"R2N",
"R2P",
"R2R",
"R2V",
"R2W",
"R2X",
"R2Y",
"R3A",
"R3B",
"R3C",
"R3E",
"R3G",
"R3H",
"R3J",
"R3K",
"R3L",
"R3M",
"R3N",
"R3P",
"R3R",
"R3S",
"R3T",
"R3V",
"R3W",
"R3X",
"R3Y",
"R4A",
"R4H",
"R4J",
"R4K",
"R4L",
"R5A",
"R5G",
"R5H",
"R6M",
"R6W",
"R7A",
"R7B",
"R7C",
"R7N",
"R8A",
"R8N",
"R9A",
"E1A",
"E1B",
"E1C",
"E1E",
"E1G",
"E1H",
"E1J",
"E1N",
"E1V",
"E1W",
"E1X",
"E2A",
"E2E",
"E2G",
"E2H",
"E2J",
"E2K",
"E2L",
"E2M",
"E2N",
"E2P",
"E2R",
"E2S",
"E2V",
"E3A",
"E3B",
"E3C",
"E3E",
"E3L",
"E3N",
"E3V",
"E3Y",
"E3Z",
"E4A",
"E4B",
"E4C",
"E4E",
"E4G",
"E4H",
"E4J",
"E4K",
"E4L",
"E4M",
"E4N",
"E4P",
"E4R",
"E4S",
"E4T",
"E4V",
"E4W",
"E4X",
"E4Y",
"E4Z",
"E5A",
"E5B",
"E5C",
"E5E",
"E5G",
"E5H",
"E5J",
"E5K",
"E5L",
"E5M",
"E5N",
"E5P",
"E5R",
"E5S",
"E5T",
"E5V",
"E6A",
"E6B",
"E6C",
"E6E",
"E6G",
"E6H",
"E6J",
"E6K",
"E6L",
"E7A",
"E7B",
"E7C",
"E7E",
"E7G",
"E7H",
"E7J",
"E7K",
"E7L",
"E7M",
"E7N",
"E7P",
"E8A",
"E8B",
"E8C",
"E8E",
"E8G",
"E8J",
"E8K",
"E8L",
"E8M",
"E8N",
"E8P",
"E8R",
"E8S",
"E8T",
"E9A",
"E9B",
"E9C",
"E9E",
"E9G",
"E9H",
"A0A",
"A0B",
"A0C",
"A0E",
"A0G",
"A0H",
"A0J",
"A0K",
"A0L",
"A0M",
"A0N",
"A0P",
"A0R",
"A1A",
"A1B",
"A1C",
"A1E",
"A1G",
"A1H",
"A1K",
"A1L",
"A1M",
"A1N",
"A1S",
"A1V",
"A1W",
"A1X",
"A1Y",
"A2A",
"A2B",
"A2H",
"A2N",
"A2V",
"A5A",
"A8A",
"B0C",
"B0E",
"B0H",
"B0J",
"B0K",
"B0L",
"B0M",
"B0N",
"B0P",
"B0R",
"B0S",
"B0T",
"B0V",
"B0W",
"B1A",
"B1B",
"B1C",
"B1E",
"B1G",
"B1H",
"B1J",
"B1K",
"B1L",
"B1M",
"B1N",
"B1P",
"B1R",
"B1S",
"B1T",
"B1V",
"B1W",
"B1X",
"B1Y",
"B2A",
"B2C",
"B2E",
"B2G",
"B2H",
"B2J",
"B2N",
"B2R",
"B2S",
"B2T",
"B2V",
"B2W",
"B2X",
"B2Y",
"B2Z",
"B3A",
"B3B",
"B3E",
"B3G",
"B3H",
"B3J",
"B3K",
"B3L",
"B3M",
"B3N",
"B3P",
"B3R",
"B3S",
"B3T",
"B3V",
"B3Z",
"B4A",
"B4B",
"B4C",
"B4E",
"B4G",
"B4H",
"B4N",
"B4P",
"B4R",
"B4V",
"B5A",
"B9A",
"X0E",
"X0G",
"X1A",
"X0A",
"X0B",
"X0C",
"K0A",
"K0B",
"K0C",
"K0E",
"K0G",
"K0H",
"K0J",
"K0K",
"K0L",
"K0M",
"K1A",
"K1B",
"K1C",
"K1E",
"K1G",
"K1H",
"K1J",
"K1K",
"K1L",
"K1M",
"K1N",
"K1P",
"K1R",
"K1S",
"K1T",
"K1V",
"K1W",
"K1X",
"K1Y",
"K1Z",
"K2A",
"K2B",
"K2C",
"K2E",
"K2G",
"K2H",
"K2J",
"K2K",
"K2L",
"K2M",
"K2P",
"K2R",
"K2S",
"K2T",
"K2V",
"K2W",
"K4A",
"K4B",
"K4C",
"K4K",
"K4M",
"K4P",
"K4R",
"K6A",
"K6H",
"K6J",
"K6K",
"K6T",
"K6V",
"K7A",
"K7C",
"K7G",
"K7H",
"K7K",
"K7L",
"K7M",
"K7N",
"K7P",
"K7R",
"K7S",
"K7V",
"K8A",
"K8B",
"K8H",
"K8N",
"K8P",
"K8R",
"K8V",
"K9A",
"K9H",
"K9J",
"K9K",
"K9L",
"K9V",
"L0A",
"L0B",
"L0C",
"L0E",
"L0G",
"L0H",
"L0J",
"L0K",
"L0L",
"L0M",
"L0N",
"L0P",
"L0R",
"L0S",
"L1A",
"L1B",
"L1C",
"L1E",
"L1G",
"L1H",
"L1J",
"L1K",
"L1L",
"L1M",
"L1N",
"L1P",
"L1R",
"L1S",
"L1T",
"L1V",
"L1W",
"L1X",
"L1Y",
"L1Z",
"L2A",
"L2E",
"L2G",
"L2H",
"L2J",
"L2M",
"L2N",
"L2P",
"L2R",
"L2S",
"L2T",
"L2V",
"L2W",
"L3B",
"L3C",
"L3K",
"L3M",
"L3P",
"L3R",
"L3S",
"L3T",
"L3V",
"L3X",
"L3Y",
"L3Z",
"L4A",
"L4B",
"L4C",
"L4E",
"L4G",
"L4H",
"L4J",
"L4K",
"L4L",
"L4M",
"L4N",
"L4P",
"L4R",
"L4S",
"L4T",
"L4V",
"L4W",
"L4X",
"L4Y",
"L4Z",
"L5A",
"L5B",
"L5C",
"L5E",
"L5G",
"L5H",
"L5J",
"L5K",
"L5L",
"L5M",
"L5N",
"L5P",
"L5R",
"L5S",
"L5T",
"L5V",
"L5W",
"L6A",
"L6B",
"L6C",
"L6E",
"L6G",
"L6H",
"L6J",
"L6K",
"L6L",
"L6M",
"L6P",
"L6R",
"L6S",
"L6T",
"L6V",
"L6W",
"L6X",
"L6Y",
"L6Z",
"L7A",
"L7B",
"L7C",
"L7E",
"L7G",
"L7J",
"L7L",
"L7M",
"L7N",
"L7P",
"L7R",
"L7S",
"L7T",
"L8E",
"L8G",
"L8H",
"L8J",
"L8K",
"L8L",
"L8M",
"L8N",
"L8P",
"L8R",
"L8S",
"L8T",
"L8V",
"L8W",
"L9A",
"L9B",
"L9C",
"L9G",
"L9H",
"L9K",
"L9L",
"L9M",
"L9N",
"L9P",
"L9R",
"L9S",
"L9T",
"L9V",
"L9W",
"L9Y",
"L9Z",
"M1B",
"M1C",
"M1E",
"M1G",
"M1H",
"M1J",
"M1K",
"M1L",
"M1M",
"M1N",
"M1P",
"M1R",
"M1S",
"M1T",
"M1V",
"M1W",
"M1X",
"M2H",
"M2J",
"M2K",
"M2L",
"M2M",
"M2N",
"M2P",
"M2R",
"M3A",
"M3B",
"M3C",
"M3H",
"M3J",
"M3K",
"M3L",
"M3M",
"M3N",
"M4A",
"M4B",
"M4C",
"M4E",
"M4G",
"M4H",
"M4J",
"M4K",
"M4L",
"M4M",
"M4N",
"M4P",
"M4R",
"M4S",
"M4T",
"M4V",
"M4W",
"M4X",
"M4Y",
"M5A",
"M5B",
"M5C",
"M5E",
"M5G",
"M5H",
"M5J",
"M5K",
"M5L",
"M5M",
"M5N",
"M5P",
"M5R",
"M5S",
"M5T",
"M5V",
"M5W",
"M5X",
"M6A",
"M6B",
"M6C",
"M6E",
"M6G",
"M6H",
"M6J",
"M6K",
"M6L",
"M6M",
"M6N",
"M6P",
"M6R",
"M6S",
"M7A",
"M7Y",
"M8V",
"M8W",
"M8X",
"M8Y",
"M8Z",
"M9A",
"M9B",
"M9C",
"M9L",
"M9M",
"M9N",
"M9P",
"M9R",
"M9V",
"M9W",
"N0A",
"N0B",
"N0C",
"N0E",
"N0G",
"N0H",
"N0J",
"N0K",
"N0L",
"N0M",
"N0N",
"N0P",
"N0R",
"N1A",
"N1C",
"N1E",
"N1G",
"N1H",
"N1K",
"N1L",
"N1M",
"N1P",
"N1R",
"N1S",
"N1T",
"N2A",
"N2B",
"N2C",
"N2E",
"N2G",
"N2H",
"N2J",
"N2K",
"N2L",
"N2M",
"N2N",
"N2P",
"N2R",
"N2T",
"N2V",
"N2Z",
"N3A",
"N3B",
"N3C",
"N3E",
"N3H",
"N3L",
"N3P",
"N3R",
"N3S",
"N3T",
"N3V",
"N3W",
"N3Y",
"N4B",
"N4G",
"N4K",
"N4L",
"N4N",
"N4S",
"N4T",
"N4V",
"N4W",
"N4X",
"N4Z",
"N5A",
"N5C",
"N5H",
"N5L",
"N5P",
"N5R",
"N5V",
"N5W",
"N5X",
"N5Y",
"N5Z",
"N6A",
"N6B",
"N6C",
"N6E",
"N6G",
"N6H",
"N6J",
"N6K",
"N6L",
"N6M",
"N6N",
"N6P",
"N7A",
"N7G",
"N7L",
"N7M",
"N7S",
"N7T",
"N7V",
"N7W",
"N7X",
"N8A",
"N8H",
"N8M",
"N8N",
"N8P",
"N8R",
"N8S",
"N8T",
"N8V",
"N8W",
"N8X",
"N8Y",
"N9A",
"N9B",
"N9C",
"N9E",
"N9G",
"N9H",
"N9J",
"N9K",
"N9V",
"N9Y",
"P0A",
"P0B",
"P0C",
"P0E",
"P0G",
"P0H",
"P0J",
"P0K",
"P0L",
"P0M",
"P0N",
"P0P",
"P0R",
"P0S",
"P0T",
"P0V",
"P0W",
"P0X",
"P0Y",
"P1A",
"P1B",
"P1C",
"P1H",
"P1L",
"P1P",
"P2A",
"P2B",
"P2N",
"P3A",
"P3B",
"P3C",
"P3E",
"P3G",
"P3L",
"P3N",
"P3P",
"P3Y",
"P4N",
"P4P",
"P4R",
"P5A",
"P5E",
"P5N",
"P6A",
"P6B",
"P6C",
"P7A",
"P7B",
"P7C",
"P7E",
"P7G",
"P7J",
"P7K",
"P8N",
"P8T",
"P9A",
"P9N",
"C0A",
"C0B",
"C1A",
"C1B",
"C1C",
"C1E",
"C1N",
"G0A",
"G0B",
"G0C",
"G0E",
"G0G",
"G0H",
"G0J",
"G0K",
"G0L",
"G0M",
"G0N",
"G0P",
"G0R",
"G0S",
"G0T",
"G0V",
"G0W",
"G0X",
"G0Y",
"G0Z",
"G1A",
"G1B",
"G1C",
"G1E",
"G1G",
"G1H",
"G1J",
"G1K",
"G1L",
"G1M",
"G1N",
"G1P",
"G1R",
"G1S",
"G1T",
"G1V",
"G1W",
"G1X",
"G1Y",
"G2A",
"G2B",
"G2C",
"G2E",
"G2G",
"G2J",
"G2K",
"G2L",
"G2M",
"G2N",
"G3A",
"G3E",
"G3G",
"G3H",
"G3J",
"G3K",
"G3L",
"G3M",
"G3Z",
"G4A",
"G4R",
"G4S",
"G4T",
"G4V",
"G4W",
"G4X",
"G4Z",
"G5A",
"G5B",
"G5C",
"G5H",
"G5J",
"G5L",
"G5M",
"G5N",
"G5R",
"G5T",
"G5V",
"G5X",
"G5Y",
"G5Z",
"G6A",
"G6B",
"G6C",
"G6E",
"G6G",
"G6H",
"G6J",
"G6K",
"G6L",
"G6P",
"G6R",
"G6S",
"G6T",
"G6V",
"G6W",
"G6X",
"G6Z",
"G7A",
"G7B",
"G7G",
"G7H",
"G7J",
"G7K",
"G7N",
"G7P",
"G7S",
"G7T",
"G7X",
"G7Y",
"G7Z",
"G8A",
"G8B",
"G8C",
"G8E",
"G8G",
"G8H",
"G8J",
"G8K",
"G8L",
"G8M",
"G8N",
"G8P",
"G8T",
"G8V",
"G8W",
"G8Y",
"G8Z",
"G9A",
"G9B",
"G9C",
"G9H",
"G9N",
"G9P",
"G9R",
"G9T",
"G9X",
"H0H",
"H0M",
"H1A",
"H1B",
"H1C",
"H1E",
"H1G",
"H1H",
"H1J",
"H1K",
"H1L",
"H1M",
"H1N",
"H1P",
"H1R",
"H1S",
"H1T",
"H1V",
"H1W",
"H1X",
"H1Y",
"H1Z",
"H2A",
"H2B",
"H2C",
"H2E",
"H2G",
"H2H",
"H2J",
"H2K",
"H2L",
"H2M",
"H2N",
"H2P",
"H2R",
"H2S",
"H2T",
"H2V",
"H2W",
"H2X",
"H2Y",
"H2Z",
"H3A",
"H3B",
"H3C",
"H3E",
"H3G",
"H3H",
"H3J",
"H3K",
"H3L",
"H3M",
"H3N",
"H3P",
"H3R",
"H3S",
"H3T",
"H3V",
"H3W",
"H3X",
"H3Y",
"H3Z",
"H4A",
"H4B",
"H4C",
"H4E",
"H4G",
"H4H",
"H4J",
"H4K",
"H4L",
"H4M",
"H4N",
"H4P",
"H4R",
"H4S",
"H4T",
"H4V",
"H4W",
"H4X",
"H4Y",
"H4Z",
"H5A",
"H5B",
"H7A",
"H7B",
"H7C",
"H7E",
"H7G",
"H7H",
"H7J",
"H7K",
"H7L",
"H7M",
"H7N",
"H7P",
"H7R",
"H7S",
"H7T",
"H7V",
"H7W",
"H7X",
"H7Y",
"H8N",
"H8P",
"H8R",
"H8S",
"H8T",
"H8Y",
"H8Z",
"H9A",
"H9B",
"H9C",
"H9E",
"H9G",
"H9H",
"H9J",
"H9K",
"H9P",
"H9R",
"H9S",
"H9W",
"H9X",
"J0A",
"J0B",
"J0C",
"J0E",
"J0G",
"J0H",
"J0J",
"J0K",
"J0L",
"J0M",
"J0N",
"J0P",
"J0R",
"J0S",
"J0T",
"J0V",
"J0W",
"J0X",
"J0Y",
"J0Z",
"J1A",
"J1E",
"J1G",
"J1H",
"J1J",
"J1K",
"J1L",
"J1M",
"J1N",
"J1S",
"J1T",
"J1X",
"J1Z",
"J2A",
"J2B",
"J2C",
"J2E",
"J2G",
"J2H",
"J2J",
"J2K",
"J2L",
"J2N",
"J2R",
"J2S",
"J2T",
"J2W",
"J2X",
"J2Y",
"J3A",
"J3B",
"J3E",
"J3G",
"J3H",
"J3L",
"J3M",
"J3N",
"J3P",
"J3R",
"J3T",
"J3V",
"J3X",
"J3Y",
"J3Z",
"J4B",
"J4G",
"J4H",
"J4J",
"J4K",
"J4L",
"J4M",
"J4N",
"J4P",
"J4R",
"J4S",
"J4T",
"J4V",
"J4W",
"J4X",
"J4Y",
"J4Z",
"J5A",
"J5B",
"J5J",
"J5K",
"J5L",
"J5M",
"J5R",
"J5T",
"J5V",
"J5W",
"J5X",
"J5Y",
"J5Z",
"J6A",
"J6E",
"J6J",
"J6K",
"J6N",
"J6R",
"J6S",
"J6T",
"J6V",
"J6W",
"J6X",
"J6Y",
"J6Z",
"J7A",
"J7B",
"J7C",
"J7E",
"J7G",
"J7H",
"J7J",
"J7K",
"J7L",
"J7M",
"J7N",
"J7P",
"J7R",
"J7T",
"J7V",
"J7X",
"J7Y",
"J7Z",
"J8A",
"J8B",
"J8C",
"J8E",
"J8G",
"J8H",
"J8L",
"J8M",
"J8N",
"J8P",
"J8R",
"J8T",
"J8V",
"J8X",
"J8Y",
"J8Z",
"J9A",
"J9B",
"J9E",
"J9H",
"J9J",
"J9L",
"J9P",
"J9T",
"J9V",
"J9X",
"J9Y",
"J9Z",
"S0A",
"S0C",
"S0E",
"S0G",
"S0H",
"S0J",
"S0K",
"S0L",
"S0M",
"S0N",
"S0P",
"S2V",
"S3N",
"S4A",
"S4H",
"S4L",
"S4N",
"S4P",
"S4R",
"S4S",
"S4T",
"S4V",
"S4W",
"S4X",
"S4Y",
"S4Z",
"S6H",
"S6J",
"S6K",
"S6V",
"S6W",
"S6X",
"S7H",
"S7J",
"S7K",
"S7L",
"S7M",
"S7N",
"S7P",
"S7R",
"S7S",
"S7T",
"S7V",
"S9A",
"S9H",
"S9V",
"S9X",
"Y0A",
"Y0B",
"Y1A"
    ]

    city_list = [
"Eastern Alberta (St. Paul)",
"Wainwright Region (Tofield)",
"Central Alberta (Stettler)",
"Western Alberta (Jasper)",
"North Central Alberta (Slave Lake)",
"Northwestern Alberta (High Level)",
"Southeastern Alberta (Drumheller)",
"International Border Region (Cardston)",
"Kananaskis Country (Claresholm)",
"Central Foothills (Sundre)",
"Northeastern Alberta (Fort Chipewyan)",
"Remote Northeast (Fitzgerald)",
"Medicine Hat Central",
"Medicine Hat South",
"Medicine Hat North",
"Taber",
"Lethbridge North",
"Lethbridge West and Central",
"Lethbridge Southeast",
"Banff",
"Coaldale",
"Strathmore",
"Brooks",
"Okotoks",
"High River",
"Canmore",
"Chestermere",
"Calgary (Rundle / Whitehorn / Monterey Park)",
"Calgary (Penbrooke Meadows / Marlborough)",
"Calgary (Forest Lawn / Dover / Erin Woods)",
"Calgary (Lynnwood Ridge / Ogden / Foothills Industrial / Great Plains)",
"Calgary (Bridgeland / Greenview / Zoo / YYC)",
"Calgary (Inglewood / Burnsland / Chinatown / East Victoria Park / Saddledome)",
"Calgary (Highfield / Burns Industrial)",
"Calgary (Queensland Downs / Lake Bonavista / Willow Park / Acadia)",
"Calgary (Thornecliffe / Tuxedo)",
"Calgary (Brentwood / Collingwood / Nose Hill)",
"Calgary (Mount Pleasant / Capitol Hill / Banff Trail)",
"Calgary (Kensington / Westmont / Parkdale / University)",
"Calgary (City Centre / Calgary Tower)",
"Calgary (Connaught / West Victoria Park)",
"Calgary (Elbow Park / Britannia / Parkhill / Mission)",
"Calgary South (Altadore / Bankview / Richmond)",
"Calgary (Oak Ridge / Haysboro / Kingsland / Windsor Park)",
"Calgary (Braeside / Woodbine)",
"Calgary (Midnapore / Sundance)",
"Calgary (Millrise / Somerset / Bridlewood / Evergreen)",
"Calgary (Douglas Glen / McKenzie Lake / Copperfield / East Shepard)",
"Calgary (Dalhousie / Edgemont / Hamptons / Hidden Valley)",
"Calgary (Montgomery / Bowness / Silver Springs / Greenwood)",
"Calgary (Rosscarrock / Wildwood / Shaganappi / Sunalta)",
"Calgary (Lakeview / Glendale / Killarney / Glamorgan)",
"Calgary (Hawkwood / Arbour Lake / Royal Oak / Rocky Ridge)",
"Calgary (Discovery Ridge / Signal Hill / Aspen Woods / Patterson / Cougar Ridge)",
"Calgary (Martindale / Taradale / Falconridge / Saddle Ridge)",
"Calgary (Sandstone / Harvest Hills / Coventry Hills / Panorama Hills / Beddington)",
"Calgary (Tuscany / Scenic Acres)",
"Calgary (Cranston)",
"Calgary Northeast",
"Calgary (Symons Valley)",
"Calgary Northwest",
"Redwood Meadows",
"Airdrie East",
"Airdrie West",
"Cochrane",
"Red Deer County",
"Innisfail",
"Olds",
"Ponoka",
"Lacombe",
"Red Deer Central",
"Red Deer North",
"Red Deer South",
"Sylvan Lake",
"Rocky Mountain House",
"Camrose",
"Beaumont",
"Edmonton (West Clareview / East Londonderry)",
"Edmonton (East North Central / West Beverly)",
"Edmonton (Central Londonderry)",
"Edmonton (West Londonderry / East Calder)",
"Edmonton (North Central / Queen Mary Park / YXD)",
"Edmonton (North and East Downtown Fringe)",
"Edmonton (North Downtown)",
"Edmonton (South Downtown / South Downtown Fringe)",
"Edmonton (North Westmount / West Calder / East Mistatim)",
"Edmonton (South Westmount / Groat Estate / East Northwest Industrial)",
"Edmonton (Glenora / SW Downtown Fringe)",
"Edmonton (North Jasper Place)",
"Edmonton (Central Jasper Place / Buena Vista)",
"Edmonton (West Northwest Industrial / Winterburn)",
"Edmonton West (West Jasper Place / West Edmonton Mall)",
"Edmonton (Central Mistatim)",
"Edmonton (Central Beverly)",
"Edmonton (East Castledowns)",
"Edmonton (Landbank / Oliver / East Lake District)",
"Edmonton (West Lake District)",
"Edmonton (North Capilano)",
"Edmonton (SE Capilano / West Southeast Industrial / East Bonnie Doon)",
"Edmonton (Central Bonnie Doon)",
"Edmonton (South Bonnie Doon / East University)",
"Edmonton (West University / Strathcona Place)",
"Edmonton (Southgate / North Riverbend)",
"Edmonton (Kaskitayo)",
"Edmonton (West Mill Woods)",
"Edmonton (East Mill Woods)",
"Edmonton Southwest",
"Edmonton (South Industrial)",
"Edmonton (East Southeast Industrial / South Clover Bar)",
"Edmonton (Riverbend)",
"Edmonton (North Clover Bar)",
"Edmonton (Meadows)",
"Edmonton (West Castledowns)",
"Edmonton (Heritage Valley)",
"Edmonton (Ellerslie)",
"Drayton Valley",
"Edson",
"Barrhead",
"Westlock",
"Whitecourt",
"Hinton",
"Spruce Grove North",
"Spruce Grove South",
"Stony Plain",
"Sherwood Park West",
"Sherwood Park Outer Southwest",
"Sherwood Park Inner Southwest",
"Sherwood Park Central",
"Sherwood Park East",
"Sherwood Park Northwest",
"Fort Saskatchewan",
"St. Albert",
"Morinville",
"Peace River",
"Grande Prairie Central",
"Grande Prairie South",
"Grande Prairie East",
"Wetaskiwin",
"Vegreville",
"Leduc",
"Devon",
"Fort McMurray Outer Central",
"Fort McMurray Inner Central",
"Fort McMurray Northwest",
"Cold Lake",
"Bonnyville",
"Athabasca",
"Lloydminster",
"Wainwright",
"Vermilion",
"Upper Columbia Region (Golden)",
"East Kootenays (Fernie)",
"Northern British Columbia (Fort Nelson)",
"Central Okanagan and High Country (Revelstoke)",
"West Kootenays (Rossland)",
"South Okanagan (Summerland)",
"Omineca and Yellowhead (Smithers)",
"Cariboo and West Okanagan (100 Mile House)",
"Chilcotin (Alexis Creek)",
"Harrison Lake Region (Agassiz)",
"North Island, Sunshine Coast, and Southern Gulf Islands (Whistler)",
"North Central Island and Bute Inlet Region (Gold River)",
"Central Island (Chemainus)",
"Juan de Fuca Shore (Sooke)",
"Inside Passage and the Queen Charlottes (Queen Charlotte City)",
"Lower Skeena (Port Edward)",
"Atlin Region (Atlin)",
"Similkameen (Hope)",
"Kimberley",
"Vernon East",
"Cranbrook",
"Salmon Arm",
"Dawson Creek",
"Vernon West",
"Fort St. John",
"Merritt",
"Nelson",
"Langley Township North",
"Castlegar",
"Kelowna East",
"Trail",
"Kamloops Southwest",
"Vernon Central",
"Kelowna North",
"Kelowna Southwest",
"Kelowna East Central",
"Kelowna Central",
"Kelowna West",
"Penticton",
"Kamloops Northwest",
"Kamloops Central and Southeast",
"Kamloops South and West",
"Williams Lake",
"Kamloops North",
"Quesnel",
"Prince George North",
"Prince George East Central",
"Prince George West Central",
"Prince George South",
"Chilliwack Central",
"Chilliwack West",
"Abbotsford Southeast",
"Abbotsford Southwest",
"Mission East",
"Maple Ridge East",
"Maple Ridge West",
"Langley Township Northwest",
"Langley Township Southwest",
"Langley City",
"Port Coquitlam Central",
"Port Coquitlam South",
"Port Coquitlam North",
"Abbotsford East",
"Port Moody",
"Coquitlam North",
"Coquitlam South",
"New Westminster Northeast",
"New Westminster Southwest (Includes Annacis Island)",
"Burnaby (East Big Bend / Stride Avenue / Edmonds / Cariboo-Armstrong)",
"Surrey North",
"Surrey East",
"Surrey Inner Northwest",
"Surrey Outer Northwest",
"Surrey Upper West",
"Surrey Lower West",
"Pitt Meadows",
"Surrey Southwest",
"White Rock",
"Delta Northeast",
"Delta East",
"Delta East Central",
"Delta Central",
"Delta Southeast",
"Delta Southwest",
"Surrey Northeast",
"Surrey South",
"Maple Ridge Northwest",
"Mission West",
"Westbank",
"Winfield",
"Langley Township East",
"Abbotsford West",
"Chilliwack East",
"Burnaby (Government Road / Lake City / SFU / Burnaby Mountain)",
"Burnaby (Parkcrest-Aubrey / Ardingley-Sprott)",
"Burnaby (Burnaby Heights / Willingdon Heights / West Central Valley)",
"Burnaby (Lakeview-Mayfield / Richmond Park / Kingsway-Beresford)",
"Burnaby (Cascade-Schou / Douglas-Gilpin)",
"Burnaby (Maywood / Marlborough / Oakalla / Windsor)",
"Burnaby (Suncrest / Sussex-Nelson / Clinton-Glenwood / West Big Bend)",
"Vancouver (North Hastings- Sunrise)",
"Vancouver (North Grandview- Woodlands)",
"Vancouver (South Hastings-Sunrise / North Renfrew- Collingwood)",
"Vancouver (South Grandview- Woodlands / NE Kensington)",
"Vancouver (SE Kensington / Victoria- Fraserview)",
"Vancouver (South Renfrew- Collingwood)",
"Vancouver (Killarney)",
"Vancouver (East Mount Pleasant)",
"Vancouver (West Kensington / NE Riley Park- Little Mountain)",
"Vancouver (SE Riley Park- Little Mountain / SW Kensington / NE Oakridge / North Sunset)",
"Vancouver (SE Oakridge / East Marpole / South Sunset)",
"Vancouver (West Mount Pleasant / West Riley Park- Little Mountain)",
"Vancouver (East Fairview / South Cambie)",
"Vancouver (Strathcona / Chinatown / Downtown Eastside)",
"Vancouver (NE Downtown / Harbour Centre / Gastown / Yaletown)",
"Vancouver (Waterfront / Coal Harbour / Canada Place)",
"Vancouver (South West End)",
"Vancouver (North West End / Stanley Park)",
"Vancouver (West Fairview / Granville Island / NE Shaughnessy)",
"Vancouver (NW Shaughnessy / East Kitsilano / Quilchena)",
"Vancouver (Central Kitsilano)",
"Vancouver (NW Arbutus Ridge)",
"Vancouver (South Shaughnessy / NW Oakridge / NE Kerrisdale / SE Arbutus Ridge)",
"Vancouver (Dunbar- Southlands / Musqueam)",
"Vancouver (SE Kerrisdale / SW Oakridge / West Marpole)",
"Vancouver (West Kitsilano / Jericho)",
"Vancouver (Chaldecutt / South University Endowment Lands)",
"Vancouver (UBC)",
"Richmond Northeast",
"Richmond Southeast",
"Richmond North",
"Richmond Central",
"Vancouver (SW Downtown)",
"Richmond South",
"Richmond (Sea Island / YVR)",
"Richmond West",
"Richmond Southwest",
"North Vancouver Outer East",
"North Vancouver Inner East",
"North Vancouver East Central",
"North Vancouver North Central",
"North Vancouver South Central",
"North Vancouver Southwest Central",
"North Vancouver Northwest Central",
"North Vancouver Southwest",
"North Vancouver Northwest",
"West Vancouver North",
"West Vancouver Southeast",
"West Vancouver South",
"West Vancouver West",
"Vancouver (Bentall Centre)",
"Vancouver (Pacific Centre)",
"Powell River",
"Squamish",
"Kitimat",
"Terrace",
"Prince Rupert",
"Saltspring Island",
"Sidney",
"Central Saanich",
"Saanich East",
"Saanich Southeast",
"Oak Bay North",
"Oak Bay South",
"Victoria North",
"Victoria South",
"Victoria Central British Columbia Provincial Government",
"Saanich South",
"Saanich North",
"Saanich Central",
"Esquimalt",
"Highlands",
"Metchosin",
"Saanich West",
"Ladysmith",
"Campbell River Outskirts",
"Courtenay Northern Outskirts",
"Qualicum Beach",
"Duncan",
"Comox",
"Courtenay Central",
"Parksville",
"Nanaimo South",
"Nanaimo Central",
"Nanaimo North",
"Nanaimo Northwest",
"Campbell River Central",
"Cedar",
"Port Alberni",
"Southeastern Manitoba (Lorette)",
"Northern Manitoba (Norway House)",
"North Interlake (Stonewall)",
"Eastern Manitoba (Beausejour)",
"South Central Manitoba (Altona)",
"South Interlake (MacGregor)",
"Riding Mountain (Neepawa)",
"Brandon Region (Killarney)",
"Western Manitoba (Swan River)",
"Southwestern Manitoba (Virden)",
"Selkirk",
"Lockport",
"Portage la Prairie",
"Winnipeg (Transcona)",
"East St. Paul",
"Winnipeg (River East North)",
"Winnipeg (St. Boniface NW)",
"Winnipeg (St. Boniface NE)",
"Winnipeg (River East Central)",
"Winnipeg (River East South)",
"Winnipeg (St. Vital North)",
"Winnipeg (St. Vital SW)",
"Winnipeg (Seven Oaks West)",
"Winnipeg (Inkster West)",
"Winnipeg (Seven Oaks East)",
"Winnipeg (Point Douglas East)",
"Winnipeg (Point Douglas West / Inkster East)",
"Winnipeg (St. James-Assiniboia NW)",
"Winnipeg (Centennial)",
"Winnipeg (Chinatown / Civic Centre / Exchange District)",
"Winnipeg (Broadway / The Forks / Portage and Main) Manitoba Provincial Government",
"Winnipeg (Sargent Park / Daniel McIntyre / Inkster SE)",
"Winnipeg (Minto / St. Mathews / Wolseley)",
"Winnipeg (St. James-Assiniboia NE / YWG)",
"Winnipeg (St. James-Assiniboia SE)",
"Winnipeg (St. James-Assiniboia SW)",
"Winnipeg (River Heights East)",
"Winnipeg (River Heights Central)",
"Winnipeg (River Heights West)",
"Winnipeg (Fort Garry NW / Tuxedo)",
"Winnipeg (Assiniboine South / Betsworth)",
"Winnipeg (Wilkes South)",
"Winnipeg (Fort Garry NE / University of Manitoba)",
"Winnipeg (Fort Garry South)",
"Winnipeg (Grassie / Pequis)",
"Winnipeg (St. Boniface South / St. Vital SE)",
"Winnipeg (Fort Garry West)",
"West St. Paul",
"Headingley East",
"Headingley West",
"Cartier",
"St. Francois Xavier",
"St. Adolphe",
"Steinbach",
"Ste. Anne",
"Morden",
"Winkler",
"Brandon Southeast",
"Brandon Southwest",
"Brandon North",
"Dauphin",
"Flin Flon",
"Thompson",
"The Pas",
"Dieppe Moncton East",
"Riverview",
"Moncton Central",
"Moncton West",
"Moncton Northwest",
"Lakeville, Shediac Bridge",
"Coverdale",
"Miramichi South",
"Miramichi North",
"Caraquet",
"Tracadie-Sheila",
"Bathurst",
"Rothesay, Quispamsis",
"Quispamsis",
"Saint John Northeast, Renforth",
"Saint John East",
"Saint John North",
"Saint John Central",
"Saint John West",
"Saint John Lakewood",
"Saint John Red Head",
"Saint John Grandview",
"Saint John Loch Lomond",
"Oromocto",
"Fredericton North",
"Fredericton South New Brunswick Provincial Government",
"Fredericton Southwest, New Maryland",
"Kingsclear",
"St. Stephen",
"Campbellton",
"Edmundston",
"Grand Falls Northeast",
"Grand Falls Central",
"Bathurst",
"Minto",
"Youngs Cove",
"Sussex",
"Smiths Creek",
"Hillsborough",
"Salisbury",
"Dorchester",
"Sackville",
"Bayfield",
"Cap-Pel�",
"Shediac",
"Cocagne",
"Bouctouche",
"Bass River",
"Saint-Antoine",
"Richibucto",
"St-Louis-de-Kent",
"Rogersville",
"Petitcodiac",
"Moores Mills",
"St. Andrews",
"St. George",
"Campobello Island",
"Grand Manan Island",
"Pennfield",
"Lepreau",
"Grand Bay-Westfield",
"Fredericton Junction",
"Gagetown",
"Hampton",
"Apohaqui",
"St. Martins",
"Kingston",
"Norton",
"Deer Island",
"Boiestown",
"Stanley",
"Durham Bridge",
"Millville",
"Nackawic",
"Canterbury",
"McAdam",
"Harvey",
"Burtts Corner",
"Baker Brook",
"Saint-Jacques",
"Saint-Basile",
"Saint-Leonard",
"Plaster Rock",
"Perth-Andover",
"Bath",
"Centreville",
"Florenceville",
"Woodstock",
"Debec",
"Hartland",
"Saint-Quentin",
"Kedgwick",
"Dalhousie",
"Balmoral",
"Belledune",
"Petit-Rocher",
"Beresford",
"Allardville",
"Saint-Isidore",
"Grande-Anse",
"Inkerman",
"Paquetville",
"Shippagan",
"Lam�que",
"Baie-Sainte-Anne",
"Blackville",
"Doaktown",
"Red Bank",
"Neguac",
"Brantville",
"Southeastern Avalon Peninsula (Ferryland)",
"Western Avalon Peninsula (Argentia)",
"Bonavista Peninsula (Bonavista)",
"Burin Peninsula (Marystown)",
"Northeast Newfoundland (Lewisporte)",
"Central Newfoundland (Bishops Falls)",
"Northern Newfoundland (Springdale)",
"Northwest Newfoundland/Eastern Labrador (Mary's Harbour)",
"Western Newfoundland (Lark Harbour)",
"Southwestern Newfoundland (Channel-Port aux Basques)",
"Port au Port Peninsula region (St. George's)",
"Central Labrador (Happy Valley-Goose Bay)",
"North/Western Labrador (Churchill Falls)",
"St. John's North",
"St. John's Northwest Newfoundland & Labrador Provincial Government",
"St. John's North Central",
"St. John's Central",
"St. John's South",
"St. John's Southwest",
"Torbay",
"Paradise",
"Portugal Cove-St. Philips",
"Mount Pearl",
"Goulds",
"Gander",
"Manuels",
"Conception Bay",
"Carbonear",
"Grand Falls",
"Windsor",
"Corner Brook",
"Stephenville",
"Labrador City",
"Clarenville",
"Deer Lake",
"North Victoria County (Dingwall)",
"West Cape Breton Island (Baddeck)",
"Canso region (Havre Boucher)",
"Mainland east shore (Lunenburg)",
"Southern Northumberland Strait (Pictou)",
"Isthmus of Chignecto (River H�bert)",
"Cobequid Bay north shore (Springhill)",
"Hants County (Shubenacadie)",
"Kings County (Kingston)",
"West Lunenburg County (New Germany)",
"West Annapolis County (Middleton)",
"Queens County (Shelburne)",
"Digby Neck (Digby)",
"Southwest Mainland (Weymouth)",
"Glace Bay",
"Port Morien",
"Louisbourg",
"Reserve Mines",
"Dominion",
"New Waterford",
"East Bay",
"Marion Bridge",
"Sydney Southwest",
"Sydney East",
"Sydney North",
"Sydney North Central",
"Sydney West",
"Sydney Central",
"Christmas Island",
"North Sydney North",
"Eskasoni",
"Big Bras d'Or",
"Alder Point",
"North Sydney South Central",
"Iona",
"Loch Lomond",
"Antigonish",
"New Glasgow",
"Fourchu",
"Truro",
"Waverley",
"Lantz",
"Enfield",
"Dartmouth Morris Lake",
"Dartmouth East Central",
"Dartmouth North Central",
"Dartmouth South Central",
"Dartmouth East",
"Dartmouth Southwest",
"Dartmouth Northwest",
"Porters Lake",
"Eastern Passage",
"Halifax Lower Harbour",
"Halifax Mid-Harbour Nova Scotia Provincial Government",
"Halifax Upper Harbour",
"Halifax Central",
"Halifax Bedford Basin",
"Halifax South Central",
"Halifax North West Arm",
"Halifax South",
"Halifax West",
"Lakeside",
"Harrietsfield",
"Tantallon",
"Bedford Southeast",
"Bedford Northwest",
"Lower Sackville South",
"Lower Sackville West",
"Lower Sackville North",
"Amherst",
"Kentville",
"Wolfville",
"Coldbrook",
"Bridgewater",
"Yarmouth",
"Port Hawkesbury",
"Central Northwest Territories (Inuvik)",
"Southwestern Northwest Territories (Fort Liard)",
"Yellowknife",
"Outer Nunavut (Iqaluit)",
"Central Nunavut (Cambridge Bay)",
"Inner Nunavut (Rankin Inlet)",
"National Capital Region (Almonte)",
"Prescott and Russell United Counties (Alfred)",
"Stormont, Dundas and Glengarry United Counties (Alexandria)",
"South Leeds and Grenville United Counties (Prescott)",
"Rideau Lakes area (Kemptville)",
"Frontenac County, Addington County, Loyalist Shores and Southwest Leeds (Inverary)",
"Renfrew County and Lanark Highlands Township (Deep River)",
"Quinte Shores, East Northumberland County & Prince Edward County (Picton)",
"Peterborough County and North Hastings County (Lakefield)",
"Kawartha lakes and Haliburton County (Bobcaygeon)",
"Government of Canada Ottawa and Gatineau offices",
"Gloucester (Blackburn Hamlet / Pine View)",
"Gloucester (West Orleans)",
"Orleans (Queenswood)",
"Ottawa (Riverview / Hawthorne)",
"Ottawa (Alta Vista)",
"Gloucester (Beacon Hill / Cyrville)",
"Ottawa (Overbrook)",
"Ottawa (Vanier)",
"Ottawa (Rockcliffe Park / New Edinburgh)",
"Ottawa (Lower Town / Sandy Hill / University of Ottawa)",
"Ottawa (Parliament Hill)",
"Ottawa (West Downtown area)",
"Ottawa (The Glebe / Ottawa South / Ottawa East)",
"Gloucester (Blossom Park / Hunt Club East / Leitrim)",
"Ottawa (Riverside Park / Hunt Club West / Riverside South / YOW)",
"Gloucester (South Orleans)",
"Gloucester South",
"Ottawa West",
"Ottawa (Westboro)",
"Ottawa (Highland Park / Carlingwood)",
"Ottawa (Britannia / Pinecrest)",
"Ottawa (Queensway / Copeland / Carlington / Carleton Heights)",
"Nepean East",
"Nepean (Davidson Heights)",
"Nepean (Bells Corners)",
"Nepean (Barrhaven)",
"Kanata (Beaverbrook / South March)",
"Kanata (Katimavik-Hazeldean / Glen Cairn)",
"Kanata (Bridlewood)",
"Ottawa (Centre Town)",
"Nepean (Fallowfield Village / Cedarhill Estates / Orchard Estates)",
"Stittsville",
"Kanata (Marchwood)",
"Kanata (Terry Fox / Palladium)",
"Kanata (North March)",
"Orleans (Fallingbrook)",
"Cumberland Township",
"Cumberland",
"Rockland",
"Manotick",
"Greely",
"Russell",
"Hawkesbury",
"Cornwall East",
"Cornwall West",
"Cornwall North",
"Elizabethtown",
"Brockville",
"Smiths Falls",
"Carleton Place",
"Gananoque",
"Perth",
"Kingston (SW Pittsburgh Township)",
"Kingston (Downtown)",
"Kingston (Reddendale / Cataraqui / Collins Bay)",
"Amherstview",
"Kingston (Westbrook / Cataraqui Woods / Cedarwood)",
"Napanee",
"Arnprior",
"Renfrew",
"Pembroke Central and northern subdivisions",
"Pembroke (Pleasant View / Fairview)",
"Petawawa",
"Belleville East",
"Belleville West",
"Belleville (SE Sidney Township / Avondale)",
"Trenton",
"Cobourg",
"Peterborough North",
"Peterborough South",
"Peterborough (Fairbairn Meadows / Jackson Heights)",
"Peterborough (Terra View Heights / Woodland Acres / Donwood)",
"Lindsay",
"West Northumberland County (Millbrook)",
"East Durham Regional Municipality (Orono)",
"West Durham Regional Municipality (Sunderland)",
"Lake Simcoe Southeast Shore (Sutton West)",
"Ontario Centre (Queensville)",
"Whitby Region (Gormley)",
"North Peel Regional Municipality (Kleinburg)",
"Lake Simcoe North Shore (Coldwater)",
"Lake Simcoe West Shore (Oro)",
"Georgian Bay South Shore (Angus)",
"Dufferin County (Shelburne)",
"Halton Regional Municipality (Campbellville)",
"East Haldimand County (Waterdown)",
"Niagara Regional Municipality (Fonthill)",
"Port Hope",
"Bowmanville East",
"Bowmanville West",
"Courtice",
"Oshawa Central",
"Oshawa Southeast",
"Oshawa Southwest",
"Oshawa East",
"Oshawa North",
"Whitby North",
"Whitby Southeast",
"Whitby Southwest",
"Whitby Central",
"Ajax Southwest",
"Ajax Northwest",
"Pickering Southwest",
"Pickering South",
"Pickering Central",
"Pickering North",
"Ajax East",
"Fort Erie",
"Niagara Falls Central",
"Niagara Falls Southeast",
"Niagara Falls West",
"Niagara Falls North",
"St. Catharines Northeast",
"St. Catharines Northwest",
"St. Catharines East",
"St. Catharines Central",
"St. Catharines Southwest",
"St. Catharines South",
"St. Catharines Southeast",
"St. Catharines West",
"Welland East",
"Welland West",
"Port Colborne",
"Grimsby",
"Markham Central",
"Markham Outer Southwest",
"Markham Southeast",
"Thornhill East",
"Orillia",
"Newmarket Southwest",
"Newmarket Northeast",
"Bradford",
"Stouffville",
"Richmond Hill Southeast",
"Richmond Hill Southwest",
"Richmond Hill North",
"Aurora",
"Woodbridge North",
"Thornhill West",
"Concord",
"Woodbridge South",
"Barrie North",
"Barrie South",
"Keswick",
"Midland",
"Richmond Hill Central",
"Mississauga (Malton)",
"Mississauga (Wildwood)",
"Mississauga (Matheson / East Rathwood)",
"Mississauga (East Applewood / East Dixie / NE Lakeview)",
"Mississauga (West Applewood / West Dixie / NW Lakeview)",
"Mississauga (West Rathwood / East Hurontario / SE Gateway)",
"Mississauga (Mississauga Valleys / East Cooksville)",
"Mississauga (West Cooksville / Fairview / City Centre / East Creditview)",
"Mississauga (West Creditview / Mavis / Erindale)",
"Mississauga (Central Lakeview)",
"Mississauga (SW Lakeview / Mineola / East Port Credit)",
"Mississauga (West Port Credit / Lorne Park / East Sheridan)",
"Mississauga (Clarkson / Southdown)",
"Mississauga (West Sheridan)",
"Mississauga (Erin Mills / Western Business Park)",
"Mississauga (Churchill Meadows / Central Erin Mills / South Streetsville)",
"Mississauga (Lisgar / Meadowvale)",
"Mississauga (YYZ)",
"Mississauga (West Hurontario / SW Gateway)",
"Mississauga (Cardiff / NE Gateway)",
"Mississauga (Courtney Park / East Gateway)",
"Mississauga (East Credit)",
"Mississauga (Meadowvale Village / West Gateway)",
"Maple",
"Markham East",
"Markham Northwest",
"Markham Northeast",
"Markham Inner Southwest",
"Oakville North",
"Oakville Northeast",
"Oakville East",
"Oakville South",
"Oakville West",
"Brampton North",
"Brampton Northwest",
"Brampton North Central",
"Brampton East",
"Brampton Central",
"Brampton Southeast",
"Brampton Southwest",
"Brampton South",
"Brampton West Central",
"Brampton West",
"King City",
"Caledon",
"Bolton",
"Georgetown",
"Acton",
"Burlington Northeast",
"Burlington North",
"Burlington East",
"Burlington West",
"Burlington Southeast",
"Burlington South",
"Burlington Southwest",
"Hamilton (Confederation Park / Nashdale / East Kentley / Riverdale / Lakely / Grayside / North Stoney Creek)",
"Hamilton (Greenford / North Gershome / West Stoney Creek)",
"Hamilton (West Kentley / McQuesten / Parkview / Hamilton Beach / East Industrial Sector / Normanhurst / Homeside / East Crown Point)",
"Hamilton (East Albion Falls / South Stoney Creek)",
"Hamilton (East Delta / Bartonville / Glenview / Rosedale / Lower King's Forest / Red Hill / Corman / Vincent / South Gershome)",
"Hamilton (West Industrial Sector / West Crown Point / North Stipley / North Gibson / Landsdale / Keith / North End / Beasley)",
"Hamilton (West Delta / Blakeley / South Stipley / South Gibson / St. Clair)",
"Hamilton (Stinson / Corktown)",
"Hamilton (Durand / Kirkendall / Chedoke Park)",
"Hamilton (Central / Strathcona / South Dundurn)",
"Hamilton (Westdale / Cootes Paradise / Ainslie Wood)",
"Hamilton (Sherwood / Huntington / Upper King's Forest / Lisgar / Berrisfield / Hampton Heights / Sunninghill)",
"Hamilton (Raleigh / Macassa / Lawfield / Thorner / Burkholme / Eastmount)",
"Hamilton (West Albion Falls / Hannon / Rymal / Trenholme / Quinndale / Templemead / Broughton / Eleanor / Randall / Rushdale / Butler / East Chappel)",
"Hamilton (Crerar / Bruleville / Hill Park / Inch Park / Centremount / Balfour / Greeningdon / Jerome)",
"Hamilton (Barnstown / West Chappel / Allison / Ryckmans / Mewburn / Sheldon / Falkirk / Carpenter / Kennedy / Southwest Outskirts)",
"Hamilton (Southam / Bonnington / Yeoville / Kernighan / Gourley / Rolston / Buchanan / Mohawk / Westcliffe / Gilbert / Gilkson / Gurnett / Fessenden / Mountview)",
"Ancaster West",
"Dundas",
"Ancaster East",
"Port Perry",
"Penetanguishene",
"Holland Landing",
"Uxbridge",
"Alliston",
"Innisfil",
"Milton",
"Orangeville North",
"Orangeville South",
"Collingwood",
"Wasaga Beach",
"Scarborough (Malvern / Rouge River)",
"Scarborough (Rouge Hill / Port Union / Highland Creek)",
"Scarborough (Guildwood / Morningside / Ellesmere)",
"Scarborough (Woburn)",
"Scarborough (Cedarbrae)",
"Scarborough (Eglinton)",
"Scarborough (Kennedy Park / Ionview / East Birchmount Park)",
"Scarborough (The Golden Mile / Clairlea / Oakridge / Birchmount Park East)",
"Scarborough (Cliffside / Cliffcrest / Scarborough Village West)",
"Scarborough (Birch Cliff / Cliffside West)",
"Scarborough (Dorset Park / Wexford Heights / Scarborough Town Centre)",
"Scarborough (Wexford / Maryvale)",
"Scarborough (Agincourt)",
"Scarborough (Clarks Corners / Tam O'Shanter / Sullivan)",
"Scarborough (Milliken / Agincourt North / Steeles East / L'Amoreaux East)",
"Scarborough (Steeles West / L'Amoreaux West)",
"Scarborough (Upper Rouge)",
"North York (Hillcrest Village)",
"North York (Fairview / Henry Farm / Oriole)",
"North York (Bayview Village)",
"North York (York Mills / Silver Hills)",
"Willowdale East (Newtonbrook)",
"Willowdale South",
"North York (York Mills West)",
"Willowdale West",
"North York (York Heights / Victoria Village / Parkway East)",
"Don Mills North",
"Don Mills South (Flemingdon Park)",
"North York (Armour Heights / Wilson Heights / Downsview North)",
"North York (Northwood Park / York University)",
"Downsview East (CFB Toronto)",
"Downsview West",
"Downsview Central",
"North York (Jane and Finch)",
"North York (Sweeney Park / Wigmore Park)",
"East York (Parkview Hill / Woodbine Gardens)",
"East York (Woodbine Heights)",
"East Toronto (The Beaches)",
"East York (Leaside)",
"East York (Thorncliffe Park)",
"East Toronto (The Danforth East)",
"East Toronto (The Danforth West / Riverdale)",
"East Toronto (India Bazaar / The Beaches West)",
"East Toronto (Studio District)",
"Central Toronto (Lawrence Park East)",
"Central Toronto (Davisville North)",
"Central Toronto (North Toronto West)",
"Central Toronto (Davisville)",
"Central Toronto (Moore Park / Summerhill East)",
"Central Toronto (Summerhill West / Rathnelly / South Hill / Forest Hill SE / Deer Park)",
"Downtown Toronto (Rosedale)",
"Downtown Toronto (St. James Town / Cabbagetown)",
"Downtown Toronto (Church and Wellesley)",
"Downtown Toronto (Regent Park / Port of Toronto)",
"Downtown Toronto (Ryerson)",
"Downtown Toronto (St. James Park)",
"Downtown Toronto (Berczy Park)",
"Downtown Toronto (Central Bay Street)",
"Downtown Toronto (Richmond / Adelaide / King)",
"Downtown Toronto (Harbourfront East / Union Station / Toronto Island)",
"Downtown Toronto (Toronto Dominion Centre / Design Exchange)",
"Downtown Toronto (Commerce Court / Victoria Hotel)",
"North York (Bedford Park / Lawrence Park West / Lawrence Manor East)",
"Central Toronto (Roselawn)",
"Central Toronto (Forest Hill North & West)",
"Central Toronto (The Annex / North Midtown / Yorkville)",
"Downtown Toronto (University of Toronto / Harbord)",
"Downtown Toronto (Kensington Market / Chinatown / Grange Park)",
"Downtown Toronto (CN Tower / King and Spadina / Railway Lands / Harbourfront West / Bathurst Quay / South Niagara / YTZ)",
"Downtown Toronto Stn A PO Boxes 25 The Esplanade (Enclave of M5E)",
"Downtown Toronto (Underground city)",
"North York (Lawrence Manor / Lawrence Heights)",
"North York (Glencairn)",
"York (Cedarvale)",
"York (Fairbank / Oakwood)",
"Downtown Toronto (Christie)",
"West Toronto (Dufferin / Dovercourt Village)",
"West Toronto (Rua A?ores / Trinity)",
"West Toronto (Brockton / Parkdale Village / Exhibition Place)",
"North York (North Park / Maple Leaf Park / Upwood Park)",
"York (Del Ray / Keelsdale / Mount Dennis / Silverthorne)",
"York (Runnymede / The Junction North)",
"West Toronto (High Park / The Junction South)",
"West Toronto (Parkdale / Roncesvalles Village)",
"West Toronto (Bloor West Village / Swansea)",
"Queen's Park Ontario Provincial Government",
"East Toronto Business Reply Mail Processing Centre 969 Eastern (Enclave of M4L)",
"Etobicoke (New Toronto / Mimico South / Humber Bay Shores)",
"Etobicoke (Alderwood / Long Branch)",
"Etobicoke (The Kingsway / Montgomery Road / Old Mill North)",
"Etobicoke (Old Mill South / King's Mill Park / Sunnylea / Humber Bay / Mimico NE / The Queensway East / Royal York South East / Kingsway Park South East)",
"Etobicoke (Mimico NW / The Queensway West / South of Bloor / Kingsway Park South West / Royal York South West)",
"Etobicoke (Islington Avenue)",
"Etobicoke (West Deane Park / Princess Gardens / Martin Grove / Islington / Cloverdale)",
"Etobicoke (Eringate / Bloordale Gardens / Old Burnhamthorpe / Markland Woods)",
"North York (Humber Summit)",
"North York (Humberlea / Emery)",
"Weston",
"Etobicoke (Westmount)",
"Etobicoke (Kingsview Village / St. Phillips / Martin Grove Gardens / Richview Gardens)",
"Etobicoke (South Steeles / Silverstone / Humbergate / Jamestown / Mount Olive / Beaumond Heights / Thistletown / Albion Gardens)",
"Etobicoke Northwest (Clairville / Humberwood / Woodbine Downs / West Humber / Kipling Heights / Rexdale / Elms / Tandridge / Old Rexdale)",
"West Haldimand (Port Dover)",
"Wellington (Elora)",
"Georgian Bay Southwest Shore (Dundalk)",
"Brant and Norfolk (Waterford)",
"Huron (Wingham)",
"Bruce Peninsula (Wiarton)",
"Oxford (Norwich)",
"Perth (Mitchell)",
"Elgin (Dorchester)",
"Middlesex (Clinton)",
"Lambton (Forest)",
"Kent (Blenheim)",
"Essex (Belle River)",
"Dunnville",
"Guelph South",
"Guelph North",
"Guelph Central",
"Guelph Northwest",
"Guelph West",
"Guelph East",
"Fergus",
"Cambridge South",
"Cambridge Central",
"Cambridge Southwest",
"Cambridge East",
"Kitchener East",
"Kitchener Northeast",
"Kitchener South Central",
"Kitchener Southwest",
"Kitchener Central",
"Kitchener North Central",
"Waterloo Southeast",
"Kitchener North",
"Waterloo South",
"Kitchener Northwest",
"Kitchener West",
"Kitchener Southeast",
"Kitchener South",
"Waterloo Southwest",
"Waterloo Northwest",
"Kincardine",
"Baden",
"Elmira",
"Cambridge Northeast",
"Cambridge Northwest",
"Cambridge West",
"Paris",
"Brantford Northeast",
"Brantford Central",
"Brantford Southeast",
"Brantford Southwest",
"Brantford Northwest",
"Caledonia",
"Simcoe",
"Delhi",
"Tillsonburg",
"Owen Sound",
"Meaford",
"Hanover",
"Woodstock Central",
"Woodstock North",
"Woodstock South",
"Listowel",
"St. Mary's",
"Stratford South",
"Stratford North",
"Ingersoll",
"Aylmer",
"Port Stanley",
"St. Thomas North",
"St. Thomas South",
"London (YXU / North and East Argyle / East Huron Heights)",
"London East (SW Argyle / Hamilton Road)",
"London (Fanshawe / Stoneybrook / Stoney Creek / Uplands / East Masonville)",
"London (West Huron Heights / Carling)",
"London (Glen Cairn)",
"London North (UWO)",
"London Central",
"London South (East Highland / North White Oaks / North Westminster)",
"London (South White Oaks / Central Westminster / East Longwoods / West Brockley)",
"London (Sunningdale / West Masonville / Medway / NE Hyde Park / East Fox Hollow)",
"London West (Central Hyde Park / Oakridge)",
"London (Southcrest / East Westmount / West Highland)",
"London (Riverbend / Woodhull / North Sharon Creek / Byron / West Westmount)",
"London (East Tempo)",
"London (Jackson / Old Victoria / Bradley / North Highbury)",
"London (South Highbury / Glanworth / East Brockley / SE Westminster)",
"London (Talbot / Lambeth / West Tempo / South Sharon Creek)",
"Goderich",
"Strathroy",
"Chatham Northwest",
"Chatham Southeast",
"Sarnia Central",
"Sarnia Southwest",
"Sarnia Northwest",
"Sarnia Southeast",
"Sarnia Northeast",
"Wallaceburg",
"Leamington",
"Essex",
"Tecumseh Outskirts",
"Windsor (East Riverside)",
"Windsor (East Forest Glade)",
"Windsor (Riverside)",
"Windsor (West Forest Glade / East Fontainbleu)",
"Tecumseh (YQG)",
"Windsor (South Walkerville / West Fontainbleu / Walker Farm / Devonshire)",
"Windsor South Central (West Walkerville / Remington Park)",
"Windsor East (East Walkerville)",
"Windsor (City Centre / NW Walkerville)",
"Windsor (University / South Cameron)",
"Windsor (Sandwich / Ojibway / West Malden)",
"Windsor South (East Malden)",
"Windsor (Roseland)",
"La Salle East",
"La Salle West",
"Tecumseh Central",
"Amherstburg",
"Kingsville",
"Nipissing Central (Burk's Falls)",
"Nipissing South (Utterson)",
"Parry Sound Mid-Shore (Bala)",
"Parry Sound South Shore (Kilworthy)",
"Parry Sound North Shore (Nobel)",
"Nipissing North (Callander)",
"Timiskaming South (Temiskaming Shores)",
"Timiskaming North (Iroquois Falls A)",
"Cochrane Region (Hearst)",
"Algoma, Sudbury District and Greater Sudbury (Chelmsford)",
"Timmins Region (South Porcupine)",
"Manitoulin (Little Current)",
"Algoma Southwest (Blind River)",
"Lake Superior East Shore (Wawa)",
"Lake Superior North Shore (Marathon)",
"Northwestern Ontario (Red Lake)",
"Rainy River Region (Emo)",
"Kenora Region (Keewatin)",
"Lake of the Woods East Shore (Ingolf)",
"North Bay South",
"North Bay Central",
"North Bay North",
"Huntsville",
"Bracebridge",
"Gravenhurst",
"Parry Sound",
"Sturgeon Falls",
"Kirkland Lake",
"Greater Sudbury (New Sudbury)",
"Greater Sudbury (Downtown / Minnow Lake)",
"Greater Sudbury (Gatchell / West End / Little Britain)",
"Greater Sudbury (Robinson / Lockerby)",
"Greater Sudbury (Lo-Ellen / McFarlane Lake)",
"Greater Sudbury (Garson)",
"Greater Sudbury (Val Caron)",
"Greater Sudbury (Hanmer)",
"Greater Sudbury (Lively)",
"Timmins Southeast",
"Timmins North",
"Timmins West",
"Elliot Lake",
"Espanola",
"Kapuskasing",
"Sault Ste. Marie East",
"Sault Ste. Marie Central",
"Sault Ste. Marie North",
"Thunder Bay Northeast",
"Thunder Bay North Central",
"Thunder Bay Central",
"Thunder Bay South Central",
"Thunder Bay North",
"Thunder Bay South",
"Thunder Bay West",
"Dryden",
"Sioux Lookout",
"Fort Frances",
"Kenora",
"Montague",
"Prince County (Portage)",
"Charlottetown Southeast Prince Edward Island Provincial Government",
"Stratford",
"Charlottetown North",
"Charlottetown West",
"Summerside",
"Capitale-Nationale (Stoneham)",
"Cap-aux-Meules",
"Gasp�sie-Sud (New Richmond)",
"Gasp�sie-Nord (Grande-Vall�e)",
"C�te-Nord/Anticosti (Schefferville)",
"Manicouagan (Baie-Trinit�)",
"Gasp�sie-Ouest (Causapscal)",
"Bas-St-Laurent- Est (Sainte-Luce)",
"Bas-St-Laurent- Ouest (Trois-Pistoles)",
"R�gion de Beauce (Saint-Prosper-De- Dorchester)",
"Chaudi�re-Sud (Disraeli)",
"Centre-du- Qu�bec-Est (Saint-Val�re)",
"Appalaches (La Pocati�re)",
"Chaudi�re-Nord (Saint-Joseph- De-Beauce)",
"Le Fjord (Forestville)",
"Saguenay- Lac-St-Jean (Alouette)",
"R�gion de Mistassini (Chambord)",
"Mauricie (Parent)",
"L'Erable (Nantes)",
"Centre-du- Qu�bec-Nord (Daveluyville)",
"Quebec Provincial Government",
"Beauport North",
"Beauport Central",
"Beauport South",
"Jean-Talon Southeast",
"Charlesbourg South",
"Quebec City Lower Riverbank",
"Quebec City Mid-Riverbank",
"Quebec City Northeast",
"Quebec City North Central",
"Quebec City South Central",
"Quebec City West",
"Quebec City East",
"Quebec City South",
"Quebec City Upper Riverbank",
"Sainte-Foy Northeast",
"Sainte-Foy Southeast",
"Sainte-Foy West",
"Cap-Rouge",
"Loretteville North",
"Loretteville South",
"Quebec City Northwest",
"L'Ancienne- Lorette Northeast",
"L'Ancienne- Lorette Southwest",
"Quebec City Inner North",
"Quebec City Outer North",
"Charlesbourg North",
"Jean-Talon Northeast",
"Jean-Talon West",
"St-Augustin- De-Desmaures",
"Saint-�mile",
"Lac-Saint-Charles",
"Pont-Rouge",
"Val-B�lair North",
"Val-B�lair South",
"Saint-Raymond",
"Donnacona",
"Baie-Saint-Paul",
"Clermont",
"Sept-�les Southeast",
"Sept-�les Northwest",
"Les �les-De-La- Madeleine",
"Sainte-Anne- Des-Monts",
"Matane",
"Gasp�",
"Baie-Comeau Northeast",
"La Malbaie",
"Port-Cartier",
"Baie-Comeau Southwest",
"Mont-Joli",
"Amqui",
"Rimouski Central",
"Rimouski Northeast",
"Rimouski Southwest",
"Rivi�re-du-Loup",
"Degelis",
"Montmagny",
"Beauceville",
"Saint-Georges Central",
"Saint-Georges Southeast",
"Saint-Georges Northwest",
"Lac-Megantic",
"Pintendre",
"Sainte-Marie",
"Thetford Mines",
"Black Lake",
"Saint-Etienne- De-Lauzon",
"Saint- Redempteur",
"Plessisville",
"Victoriaville Central",
"Victoriaville South",
"Victoriaville East",
"Victoriaville Northwest",
"L�vis North",
"L�vis South",
"Charny",
"Saint-Jean- Chrysostome",
"Saint-Nicolas",
"La Baie",
"Chicoutimi North",
"Chicoutimi East",
"Chicoutimi West",
"Chicoutimi Southwest",
"Laterri�re",
"Saint-Ambroise",
"Jonqui�re Northeast",
"Jonqui�re Southeast",
"Jonqui�re Central",
"Jonqui�re Southwest",
"Jonqui�re Northwest",
"Jonqui�re West",
"Alma Southeast",
"Alma Southwest",
"Alma North",
"M�tabetchouan- Lac-a-la-Croix",
"Roberval",
"Saint-Prime",
"Saint-F�licien",
"Dolbeau- Mistassini",
"Albanel",
"H�bertville",
"Chibougamau",
"Cap-de-la- Madeleine Central and southeast",
"Cap-de-la- Madeleine Northeast",
"Cap-de-la- Madeleine West",
"Trois-Rivi�res Central",
"Trois-Rivi�res Northeast",
"Trois-Rivi�res East",
"Trois-Rivi�res South",
"Trois-Rivi�res West",
"Becancour",
"Shawinigan Central",
"Shawinigan Southeast",
"Shawinigan Northwest",
"Grand-M�re",
"La Tuque",
"Reserved (Santa Claus)",
"Akwesasne Region (Akwesasne)",
"Pointe-Aux-Trembles",
"Montreal East",
"Rivi�re-des-Prairies Northeast",
"Rivi�re-Des-Prairies Southwest",
"Montreal North North",
"Montreal North South",
"Anjou West",
"Anjou East",
"Mercier North",
"Mercier West",
"Mercier Southeast",
"Saint-L�onard North",
"Saint-L�onard West",
"Saint-L�onard Southeast",
"Rosemont North",
"Maisonneuve",
"Hochelaga",
"Rosemont Central",
"Rosemont South",
"Saint-Michel West",
"Saint-Michel East",
"Ahuntsic North",
"Ahuntsic Central",
"Villeray Northeast",
"Petite-Patrie Northeast",
"Plateau Mont-Royal North",
"Plateau Mont-Royal North Central",
"Centre-Sud North",
"Centre-Sud South",
"Ahuntsic East",
"Ahuntsic Southeast",
"Villeray West",
"Villeray Southeast",
"Petite-Patrie Southwest",
"Plateau Mont-Royal West",
"Outremont",
"Plateau Mont-Royal South Central",
"Plateau Mont-Royal Southeast",
"Old Montreal",
"Downtown Montreal Northeast",
"Downtown Montreal North",
"Downtown Montreal East",
"Griffintown (Includes �le Notre-Dame & �le Sainte-H�l�ne)",
"L'�le-Des-Soeurs",
"Downtown Montreal Southeast",
"Downtown Montreal South & West",
"Petite-Bourgogne",
"Pointe-Saint-Charles",
"Ahuntsic Southwest",
"Cartierville Northeast",
"Parc-Extension",
"Mount Royal North",
"Mount Royal Central",
"C�te-des-Neiges North",
"C�te-des-Neiges Northeast",
"C�te-des-Neiges East",
"C�te-des-Neiges Southwest",
"Hampstead",
"Westmount West",
"Westmount East",
"Notre-Dame-de-Gr�ce Northeast",
"Notre-Dame-de-Gr�ce Southwest",
"Saint-Henri",
"Ville �mard",
"Verdun North",
"Verdun South",
"Cartierville Central",
"Cartierville Southwest",
"Saint-Laurent Inner Northeast",
"Saint-Laurent East",
"Saint-Laurent Outer Northeast",
"Mount Royal South",
"Saint-Laurent Central",
"Saint-Laurent Southwest",
"Saint-Laurent Southeast",
"C�te-Saint-Luc East",
"C�te-Saint-Luc West",
"Montreal West",
"Dorval Central",
"Tour de la Bourse",
"Place Bonaventure",
"Place Desjardins",
"Duvernay-Est",
"Saint-Fran?ois",
"Saint-Vincent-de-Paul",
"Duvernay",
"Pont-Viau",
"Auteuil West",
"Auteuil Northeast",
"Auteuil South",
"Sainte-Rose",
"Vimont",
"Laval-des-Rapides",
"Fabreville",
"Laval-sur-le-Lac",
"Chomedey Northeast",
"Chomedey Northwest",
"Chomedey East",
"Chomedey South",
"Sainte-Doroth�e",
"�les-Laval",
"LaSalle Northwest",
"LaSalle Southeast",
"Saint-Pierre",
"Lachine East",
"Lachine West",
"Roxboro",
"Pierrefonds",
"Dollard-Des- Ormeaux Northwest",
"Dollard-Des- Ormeaux East",
"L'�le Bizard Northeast",
"L'�le-Bizard Southwest",
"Dollard-Des- Ormeaux Southwest",
"Sainte-Genevi�ve",
"Kirkland",
"Senneville",
"Dorval Outskirts",
"Pointe-Claire",
"L'�le-Dorval",
"Beaconsfield",
"Sainte-Anne-De- Bellevue",
"Centre-du- Qu�bec-Sud (Warwick)",
"Estrie-Est (Stanstead)",
"Centre-du- Qu�bec-Ouest (Saint- Bonaventure)",
"Estrie-Ouest (Fulford)",
"Bois-Francs-Nord (Odanak)",
"Bois-Francs-Sud (Saint-Nazaire- D'Acton)",
"Mont�r�gie-Est (Bedford)",
"Lanaudi�re-Nord (Saint-Esprit)",
"Mont�r�gie-Nord (Saint-Antoine- Sur-Richelieu)",
"Nunavik (Kuujjuaq)",
"R�gion d'Oka (Oka)",
"Vaudreuil- Soulanges (Coteau-du-Lac)",
"Lanaudi�re-Sud (Pr�vost)",
"Mont�r�gie- Ouest (Saint-Anicet)",
"Laurentides-Nord (Montcalm)",
"Laurentides-Sud (Ch�n�ville)",
"Outaouais-Nord (Ferme-Neuve)",
"Outaouais-Sud (Thurso)",
"Abitibi- T�miscamingue- Est (Radisson)",
"Abitibi- T�miscamingue- Ouest (Guigues)",
"Coaticook",
"Sherbrooke Northeast",
"Sherbrooke East",
"Sherbrooke Central",
"Sherbrooke North",
"Sherbrooke West",
"Sherbrooke Northwest",
"Sherbrooke Southeast",
"Rock Forest",
"Windsor",
"Asbestos",
"Magog",
"Saint-Cyrille- De-Wendover",
"Drummondville Southeast",
"Drummondville South",
"Drummondville Central",
"Drummondville Northwest",
"Granby Central",
"Granby East",
"Granby West",
"Cowansville",
"Bromont",
"Farnham",
"Saint-Hyacinthe Northwest",
"Saint-Hyacinthe Southwest",
"Saint-Hyacinthe East",
"Saint-Luc",
"Saint-Jean- sur-Richelieu East",
"Saint-Jean- sur-Richelieu West",
"Saint-Jean- sur-Richelieu North",
"Saint-Jean- sur-Richelieu Central",
"Sainte-Julie",
"Beloeil West",
"Beloeil East",
"Chambly",
"Marieville",
"Saint-Basile- Le-Grand",
"Sorel Central",
"Sorel Southwest",
"Nicolet",
"Saint-Bruno",
"Varennes",
"Saint-Hubert Central",
"Saint-Hubert East",
"Boucherville",
"Longueuil North",
"Longueuil West",
"Longueuil Central",
"Longueuil Southwest",
"Longueuil Southeast",
"Longueuil East",
"Longueuil Northeast",
"Saint-Lambert North",
"Saint-Lambert Central",
"Saint-Lambert South",
"Saint-Hubert West",
"Greenfield Park",
"Brossard Northwest",
"Brossard Southwest",
"Brossard South",
"Brossard Northeast",
"Saint-Constant",
"Delson",
"Saint-Sophie",
"Saint-Colomban",
"Saint-J�r�me West",
"Saint-Lin- Laurentides",
"La Prairie",
"Lavaltrie",
"Louiseville",
"L'Assomption",
"L'�piphanie",
"Repentigny Northeast",
"Repentigny West",
"Repentigny South",
"Joliette",
"Ch�teauguay North",
"Ch�teauguay South",
"Beauharnois",
"Mercier",
"Salaberry-de- Valleyfield North",
"Salaberry-de- Valleyfield South",
"Terrebonne East",
"Terrebonne Central",
"Terrebonne Northwest",
"Terrebonne Southwest",
"Sainte-Th�r�se- de-Blainville Northeast",
"Sainte-Th�r�se- de-Blainville East",
"Sainte-Th�r�se- de-Blainville North",
"Sainte-Th�r�se- de-Blainville Northwest",
"Sainte-Th�r�se- de-Blainville Central",
"Sainte-Th�r�se- de-Blainville South",
"Sainte-Th�r�se- de-Blainville Southwest",
"Mirabel Northeast",
"Mascouche Extremities",
"Mascouche Central",
"La Plaine",
"Mirabel Southwest",
"Saint-Eustache Northeast",
"Saint-Eustache Southwest",
"Vaudreuil- Dorion RCM",
"Vaudreuil- Dorion",
"Valleyfield",
"Saint-J�r�me North",
"Saint-J�r�me Southeast",
"Saint-Hippolyte",
"Sainte-Ad�le",
"Sainte-Agathe- Des-Monts",
"Mont-Tremblant",
"Chatham",
"Lachute",
"Buckingham",
"Masson-Angers",
"Val-des-Monts",
"Gatineau Southeast",
"Gatineau Northeast",
"Gatineau Southwest",
"Gatineau Northwest",
"Hull Southeast",
"Hull Central",
"Hull North",
"Hull Southwest",
"Chelsea",
"Maniwaki",
"Aylmer South",
"Aylmer North",
"Mont-Laurier",
"Val-d'Or",
"Amos",
"Ville-Marie",
"Rouyn-Noranda South",
"Rouyn-Noranda North",
"La Sarre",
"Yorkton Region (Melville)",
"Southeastern Saskatchewan (Carlyle)",
"Eastern Saskatchewan (Melfort)",
"South Central Saskatchewan (Fort Qu'Appelle)",
"Southern Saskatchewan (Assiniboia)",
"Northern Saskatchewan (La Ronge)",
"Central Saskatchewan (Humboldt)",
"Western Saskatchewan (Kindersley)",
"Northwestern Saskatchewan (Battleford)",
"Southwestern Saskatchewan (Maple Creek)",
"Northeastern Saskatchewan (Creighton)",
"Buena Vista",
"Yorkton",
"Estevan",
"Weyburn",
"Regina East",
"Regina Northeast and East Central",
"Regina Central",
"Regina North Central",
"Regina South Saskatchewan Provincial Government",
"Regina West",
"Regina Southeast",
"Regina Southwest",
"Regina Northwest",
"Regina Outer Northwest",
"Regina Northeast",
"Moose Jaw Southeast",
"Moose Jaw Northeast",
"Moose Jaw West",
"Prince Albert Central",
"Prince Albert Southwest",
"Prince Albert East",
"Saskatoon East Central",
"Saskatoon South Central",
"Saskatoon North Central",
"Saskatoon West",
"Saskatoon Southwest",
"Saskatoon Northeast Central",
"Saskatoon North",
"Saskatoon Northwest",
"Saskatoon Northeast",
"Saskatoon South",
"Saskatoon Southeast",
"North Battleford",
"Swift Current",
"Lloydminster",
"Meadow Lake",
"Southeastern Yukon (Watson Lake)",
"Central Yukon (Dawson City)",
"Whitehorse"
    ]

    state_list = [
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "Alberta",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "British Columbia",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "Manitoba",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "New Brunswick",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Newfoundland and Labrador",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Nova Scotia",
            "Northwest Territory",
            "Northwest Territory",
            "Northwest Territory",
            "Nunavut Territory",
            "Nunavut Territory",
            "Nunavut Territory",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Ontario",
            "Prince Edward Island",
            "Prince Edward Island",
            "Prince Edward Island",
            "Prince Edward Island",
            "Prince Edward Island",
            "Prince Edward Island",
            "Prince Edward Island",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Quebec",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Saskatchewan",
            "Yukon",
            "Yukon",
            "Yukon"
    ]

    for a in range(0, len(zip_code_list)):
        state = State.objects.get(name=state_list[a])
        City.objects.create(postcode=int(zip_code_list[a]),
                            name=city_list[a],
                            state_id=state.id,
                            country_id=3
        )
